import type { InterviewQuestion } from '../../types/interviewQuestion'
import type { InterviewSessionQuestionProgress } from '../../types/interviewSession'
import type { JobRequirement } from '../../types/jobRequirement'
import { Badge } from '../ui/Badge'
import { Button } from '../ui/Button'

const label = (value: string) => value.toLocaleLowerCase().replaceAll('_', ' ').replace(/^./, (letter) => letter.toUpperCase())
export function CurrentInterviewQuestion({ question, progress, requirements, active, hasPrevious, hasNext, onAsked, onSkipped, onPrevious, onNext }: { question: InterviewQuestion; progress: InterviewSessionQuestionProgress; requirements: JobRequirement[]; active: boolean; hasPrevious: boolean; hasNext: boolean; onAsked: () => void; onSkipped: () => void; onPrevious: () => void; onNext: () => void }) {
  const mapped = requirements.filter((item) => question.requirementIds.includes(item.id)).map((item) => item.label)
  return <section className="rounded-aura-lg border border-marine/20 bg-white p-5 shadow-aura-sm md:p-7" aria-live="polite"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex flex-wrap gap-2"><Badge tone="accent">Question {question.order}</Badge><Badge tone="neutral">{label(question.category)}</Badge><span className="self-center text-xs text-aura-text-muted">{question.estimatedMinutes} minutes · {label(progress.status)}</span></div><Badge tone={question.priority === 'CORE' ? 'success' : 'warning'}>{label(question.priority)}</Badge></div><h1 className="mb-0 mt-5 text-2xl font-semibold leading-9 text-depth md:text-3xl md:leading-10">{question.text}</h1>{question.generationReason ? <p className="mb-0 mt-4 text-sm leading-6 text-aura-text-secondary"><strong className="text-harbor">Why this question:</strong> {question.generationReason}</p> : null}<div className="mt-5 grid gap-3 border-t border-harbor/10 pt-4 sm:grid-cols-2">{question.interviewerGuidance ? <div><p className="m-0 text-xs font-semibold text-aura-text-muted">Interviewer guidance</p><p className="mb-0 mt-1 text-sm leading-6 text-depth">{question.interviewerGuidance}</p></div> : null}{question.expectedEvidence ? <div><p className="m-0 text-xs font-semibold text-aura-text-muted">Expected evidence</p><p className="mb-0 mt-1 text-sm leading-6 text-depth">{question.expectedEvidence}</p></div> : null}{mapped.length ? <div className="sm:col-span-2"><p className="m-0 text-xs font-semibold text-aura-text-muted">Related requirements</p><p className="mb-0 mt-1 text-sm text-depth">{mapped.join(' · ')}</p></div> : null}</div><div className="mt-6 flex flex-wrap items-center gap-2"><Button disabled={!active || progress.status !== 'CURRENT'} onClick={onAsked}>Mark as asked</Button><Button variant="secondary" disabled={!active || progress.status !== 'CURRENT'} onClick={onSkipped}>Skip question</Button><div className="ml-auto flex gap-2"><Button variant="ghost" disabled={!hasPrevious} onClick={onPrevious}>Previous</Button><Button variant="ghost" disabled={!hasNext} onClick={onNext}>Next</Button></div></div></section>
}
