import { useEffect, useState } from 'react'
import { Plus, X } from 'lucide-react'
import type { InterviewSessionQuestionProgress } from '../../types/interviewSession'
import { Button } from '../ui/Button'

export function InterviewQuestionNotes({ progress, editable, onSave, onAddFollowUp, onRemoveFollowUp }: { progress: InterviewSessionQuestionProgress; editable: boolean; onSave: (notes: string) => void; onAddFollowUp: (text: string) => void; onRemoveFollowUp: (index: number) => void }) {
  const [notes, setNotes] = useState(progress.interviewerNotes); const [followUp, setFollowUp] = useState('')
  useEffect(() => setNotes(progress.interviewerNotes), [progress.interviewerNotes, progress.questionId])
  return <section className="rounded-aura-md border border-harbor/15 bg-white p-5"><label className="text-sm font-semibold text-depth">Interviewer notes<textarea className="mt-2 min-h-40 w-full resize-y rounded-aura-sm border border-harbor/20 px-3 py-2 text-sm leading-6 text-depth focus:border-marine focus:outline-none focus:ring-2 focus:ring-glacier/35 disabled:bg-frost" disabled={!editable} maxLength={5000} placeholder="Capture evidence, examples, and important details from the candidate’s answer." value={notes} onChange={(event) => setNotes(event.target.value)} onBlur={() => onSave(notes)} /></label><div className="mt-4"><p className="m-0 text-sm font-semibold text-depth">Follow-up prompts</p><div className="mt-2 grid gap-2">{progress.followUpNotes.map((item, index) => <div className="flex items-center gap-2 rounded-aura-sm bg-frost p-2 text-sm text-depth" key={`${item}-${index}`}><span className="flex-1">{item}</span>{editable ? <button className="text-aura-text-muted hover:text-aura-danger" onClick={() => onRemoveFollowUp(index)} aria-label={`Remove follow-up ${index + 1}`}><X size={14} /></button> : null}</div>)}</div>{editable ? <div className="mt-2 flex gap-2"><input className="min-w-0 flex-1 rounded-aura-sm border border-harbor/20 px-3 text-sm focus:outline-none focus:ring-2 focus:ring-glacier" maxLength={300} placeholder="Add a follow-up prompt" value={followUp} onChange={(event) => setFollowUp(event.target.value)} /><Button variant="secondary" disabled={followUp.trim().length < 3} onClick={() => { onSave(notes); onAddFollowUp(followUp); setFollowUp('') }}><Plus size={14} />Add</Button></div> : null}</div></section>
}
