import { useState, type FormEvent } from 'react'
import type { InterviewQuestion, InterviewQuestionCategory, InterviewQuestionPriority } from '../../types/interviewQuestion'
import { Button } from '../ui/Button'

export type InterviewQuestionDraft = Pick<InterviewQuestion, 'text' | 'category' | 'priority' | 'estimatedMinutes' | 'interviewerGuidance' | 'expectedEvidence'>
const categories: InterviewQuestionCategory[] = ['INTRODUCTION', 'ROLE_REQUIREMENT', 'TECHNICAL', 'EXPERIENCE', 'BEHAVIORAL', 'PROBLEM_SOLVING', 'SCREENING_FOLLOW_UP', 'MISSING_EVIDENCE', 'CANDIDATE_QUESTION']
const priorities: InterviewQuestionPriority[] = ['CORE', 'FOLLOW_UP', 'OPTIONAL']
const inputClass = 'mt-1.5 w-full rounded-aura-sm border border-harbor/20 bg-white px-3 py-2 text-sm text-depth focus:border-marine focus:outline-none focus:ring-2 focus:ring-glacier/35'
const label = (value: string) => value.toLocaleLowerCase().replaceAll('_', ' ').replace(/^./, (letter) => letter.toUpperCase())

export function InterviewQuestionEditor({ initial, submitLabel, onSubmit, onCancel }: { initial?: InterviewQuestionDraft; submitLabel: string; onSubmit: (draft: InterviewQuestionDraft) => void; onCancel: () => void }) {
  const [draft, setDraft] = useState<InterviewQuestionDraft>(initial ?? { text: '', category: 'ROLE_REQUIREMENT', priority: 'CORE', estimatedMinutes: 4, interviewerGuidance: '', expectedEvidence: '' })
  const valid = draft.text.trim().length >= 10 && draft.estimatedMinutes >= 1 && draft.estimatedMinutes <= 15
  function submit(event: FormEvent) { event.preventDefault(); if (valid) onSubmit({ ...draft, text: draft.text.trim() }) }
  return <form onSubmit={submit}><div className="grid gap-4"><label className="text-sm font-semibold text-depth">Question<textarea className={`${inputClass} min-h-28 resize-y`} value={draft.text} onChange={(event) => setDraft({ ...draft, text: event.target.value })} /><span className="mt-1 block text-xs font-normal text-aura-text-muted">At least 10 characters.</span></label><div className="grid gap-4 sm:grid-cols-3"><label className="text-sm font-semibold text-depth">Category<select className={inputClass} value={draft.category} onChange={(event) => setDraft({ ...draft, category: event.target.value as InterviewQuestionCategory })}>{categories.map((item) => <option key={item} value={item}>{label(item)}</option>)}</select></label><label className="text-sm font-semibold text-depth">Priority<select className={inputClass} value={draft.priority} onChange={(event) => setDraft({ ...draft, priority: event.target.value as InterviewQuestionPriority })}>{priorities.map((item) => <option key={item} value={item}>{label(item)}</option>)}</select></label><label className="text-sm font-semibold text-depth">Estimated time<input className={inputClass} type="number" min="1" max="15" value={draft.estimatedMinutes} onChange={(event) => setDraft({ ...draft, estimatedMinutes: Number(event.target.value) })} /></label></div><label className="text-sm font-semibold text-depth">Interviewer guidance<textarea className={`${inputClass} min-h-20`} value={draft.interviewerGuidance ?? ''} onChange={(event) => setDraft({ ...draft, interviewerGuidance: event.target.value })} /></label><label className="text-sm font-semibold text-depth">Expected evidence<textarea className={`${inputClass} min-h-20`} value={draft.expectedEvidence ?? ''} onChange={(event) => setDraft({ ...draft, expectedEvidence: event.target.value })} /></label></div><div className="mt-6 flex justify-end gap-2"><Button variant="ghost" onClick={onCancel}>Cancel</Button><Button type="submit" disabled={!valid}>{submitLabel}</Button></div></form>
}
