import { Link } from 'react-router-dom'
import type { InterviewListItem } from '../../store/demoSelectors'
import { formatInterviewDate, formatInterviewMode, formatInterviewStatus, formatInterviewTime } from '../../utils/helpers'
import { Badge } from '../ui/Badge'
import { Card } from '../ui/Card'
import { useDemoStore } from '../../hooks/useDemoStore'
import { selectInterviewQuestionPreparationStatus } from '../../store/demoSelectors'

export function InterviewCard({ item, confirmedLabel = false }: { item: InterviewListItem; confirmedLabel?: boolean }) {
  const { state } = useDemoStore()
  const { interview, candidate, job } = item
  const preparation = selectInterviewQuestionPreparationStatus(state, interview.id)
  return <Card className="grid gap-4 p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="m-0 text-base font-semibold text-depth">{candidate.fullName}</h3><p className="mb-0 mt-1 text-sm text-aura-text-secondary">{job.title}</p><p className="mb-0 mt-1 text-xs font-semibold text-harbor">{preparation === 'APPROVED' ? 'Plan approved' : preparation === 'DRAFT_READY' ? 'Questions ready' : preparation === 'FAILED' ? 'Preparation failed' : 'Questions preparing'}</p></div><Badge tone={interview.status === 'COMPLETED' ? 'success' : interview.status === 'CANCELLED' ? 'neutral' : 'accent'}>{confirmedLabel ? 'Interview confirmed' : formatInterviewStatus(interview.status)}</Badge></div><dl className="grid grid-cols-2 gap-3 border-y border-harbor/10 py-3"><div className="col-span-2"><dt className="text-[10px] font-bold uppercase tracking-wide text-aura-text-muted">Schedule</dt><dd className="mb-0 mt-1 text-sm font-semibold text-depth">{formatInterviewDate(interview.scheduledStart)} · {formatInterviewTime(interview.scheduledStart)}–{formatInterviewTime(interview.scheduledEnd)}</dd><dd className="m-0 text-xs text-aura-text-muted">{interview.timezone}</dd></div><div><dt className="text-[10px] font-bold uppercase tracking-wide text-aura-text-muted">Mode</dt><dd className="mb-0 mt-1 text-sm text-depth">{formatInterviewMode(interview.mode ?? 'VIDEO')}</dd></div><div><dt className="text-[10px] font-bold uppercase tracking-wide text-aura-text-muted">Interviewers</dt><dd className="mb-0 mt-1 text-sm text-depth">{interview.interviewers.map((person) => person.name).join(', ')}</dd></div></dl><div className="flex flex-wrap gap-4"><Link className="text-sm font-semibold text-harbor no-underline focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-glacier" to={`/interviews/${interview.id}`}>View interview</Link>{interview.status === 'SCHEDULED' ? <Link className="text-sm font-semibold text-harbor" to={`/interviews/${interview.id}/questions`}>{preparation === 'APPROVED' ? 'View plan' : 'Review questions'}</Link> : null}</div></Card>
}
