import { useState } from 'react'
import { Link } from 'react-router-dom'
import type { InterviewQuestionSet } from '../../types/interviewQuestionSet'
import type { InterviewQuestionSetReadiness } from '../../utils/interviewQuestionSetReadiness'
import { formatDateTime } from '../../utils/helpers'
import { Button } from '../ui/Button'
import { Card } from '../ui/Card'
import { Dialog } from '../ui/Dialog'

const sessionLinkClass = 'mt-5 inline-flex h-10 w-full items-center justify-center rounded-aura-sm bg-glacier px-4 text-sm font-semibold text-depth no-underline transition-all hover:bg-glacier/85 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-glacier/70'

export function InterviewQuestionApproval({ questionSet, readiness, sessionPath, onApprove, onRegenerate }: { questionSet: InterviewQuestionSet; readiness: InterviewQuestionSetReadiness; sessionPath: string; onApprove: () => void; onRegenerate: () => void }) {
  const [approveOpen, setApproveOpen] = useState(false)
  const [regenerateOpen, setRegenerateOpen] = useState(false)
  if (questionSet.status === 'APPROVED') return <Card className="border-aura-success/25 bg-aura-success-soft/35 p-5"><h2 className="m-0 text-base font-semibold text-depth">Plan approved</h2><p className="mb-0 mt-2 text-sm text-aura-text-secondary">{readiness.questionCount} questions · {readiness.estimatedMinutes} minutes</p><p className="mb-0 mt-1 text-xs text-aura-text-muted">{questionSet.approvedBy} · {questionSet.approvedAt ? formatDateTime(questionSet.approvedAt) : '—'}</p><Link className={sessionLinkClass} to={sessionPath}>Go to interview session</Link></Card>
  return <><Card className="p-5"><h2 className="m-0 text-base font-semibold text-depth">Approval</h2>{readiness.blockingIssues.length ? <div className="mt-4 rounded-aura-sm bg-aura-danger-soft p-3"><p className="m-0 text-xs font-bold uppercase tracking-wide text-aura-danger">Resolve before approval</p><ul className="mb-0 mt-2 pl-5 text-sm text-aura-danger">{readiness.blockingIssues.map((issue) => <li key={issue}>{issue}</li>)}</ul></div> : null}{readiness.warnings.length ? <ul className="mb-0 mt-4 pl-5 text-xs leading-5 text-aura-warning">{readiness.warnings.map((warning) => <li key={warning}>{warning}</li>)}</ul> : null}<Button className="mt-5 w-full" disabled={!readiness.ready} onClick={() => setApproveOpen(true)}>Approve plan</Button><Button className="mt-2 w-full" variant="ghost" onClick={() => setRegenerateOpen(true)}>Regenerate</Button></Card><Dialog open={approveOpen} title="Approve interview question plan?" onClose={() => setApproveOpen(false)}><p className="mt-0 text-sm leading-6 text-aura-text-secondary">The plan becomes read-only after approval.</p><div className="mt-6 flex justify-end gap-2"><Button variant="ghost" onClick={() => setApproveOpen(false)}>Cancel</Button><Button onClick={() => { onApprove(); setApproveOpen(false) }}>Approve plan</Button></div></Dialog><Dialog open={regenerateOpen} title="Regenerate interview questions?" onClose={() => setRegenerateOpen(false)}><p className="mt-0 text-sm leading-6 text-aura-text-secondary">This replaces the draft and discards manual edits.</p><div className="mt-6 flex justify-end gap-2"><Button variant="ghost" onClick={() => setRegenerateOpen(false)}>Cancel</Button><Button variant="secondary" onClick={() => { onRegenerate(); setRegenerateOpen(false) }}>Regenerate</Button></div></Dialog></>
}
