import { Link } from 'react-router-dom'
import type { InterviewSessionStatus } from '../../types/interviewSession'
import { Badge } from '../ui/Badge'
import { Button } from '../ui/Button'
import { InterviewSessionTimer } from './InterviewSessionTimer'

export function InterviewSessionControls({ interviewId, status, formattedElapsed, elapsedSeconds, scheduledMinutes, onStart, onPause, onResume, onComplete }: { interviewId: string; status: InterviewSessionStatus; formattedElapsed: string; elapsedSeconds: number; scheduledMinutes: number; onStart: () => void; onPause: () => void; onResume: () => void; onComplete: () => void }) {
  return <div><div className="flex items-center justify-between gap-3"><div><p className="m-0 text-[10px] font-bold uppercase tracking-wide text-aura-text-muted">Session status</p><h2 className="mb-0 mt-1 text-lg font-semibold text-depth">{status === 'NOT_STARTED' ? 'Ready to begin' : status === 'IN_PROGRESS' ? 'Interview in progress' : status === 'PAUSED' ? 'Interview paused' : 'Interview completed'}</h2></div><Badge tone={status === 'COMPLETED' ? 'success' : status === 'PAUSED' ? 'warning' : 'accent'}>{status.toLocaleLowerCase().replace('_', ' ')}</Badge></div><div className="mt-4"><InterviewSessionTimer formattedElapsed={formattedElapsed} elapsedSeconds={elapsedSeconds} scheduledMinutes={scheduledMinutes} /></div>{status === 'PAUSED' ? <p className="mb-0 mt-3 text-xs text-aura-text-secondary">The active timer is paused. Notes can still be reviewed and updated.</p> : null}<div className="mt-4 grid gap-2">{status === 'NOT_STARTED' ? <Button onClick={onStart}>Start interview</Button> : status === 'IN_PROGRESS' ? <><Button onClick={onPause}>Pause interview</Button><Button variant="secondary" onClick={onComplete}>Complete interview</Button></> : status === 'PAUSED' ? <><Button onClick={onResume}>Resume interview</Button><Button variant="secondary" onClick={onComplete}>Complete interview</Button></> : null}<Link className="inline-flex h-10 items-center justify-center text-sm font-semibold text-harbor" to={`/interviews/${interviewId}`}>Back to interview</Link></div></div>
}
