import { CheckCircle2, Circle, AlertCircle } from 'lucide-react'
import type { InterviewQuestionSet } from '../../types/interviewQuestionSet'
import type { JobRequirement } from '../../types/jobRequirement'
import type { InterviewQuestionSetReadiness } from '../../utils/interviewQuestionSetReadiness'
import { Card } from '../ui/Card'

export function InterviewQuestionCoverage({ questionSet, requirements, readiness }: { questionSet: InterviewQuestionSet; requirements: JobRequirement[]; readiness: InterviewQuestionSetReadiness }) {
  const categories = questionSet.questions.reduce<Record<string, number>>((counts, question) => ({ ...counts, [question.category]: (counts[question.category] ?? 0) + 1 }), {})
  return <Card className="p-5"><h2 className="m-0 text-base font-semibold text-depth">Interview plan coverage</h2><div className="mt-4 grid gap-2">{requirements.filter((item) => item.importance !== 'SUPPORTING').map((requirement) => { const covered = readiness.coveredRequirementIds.includes(requirement.id); const missingRequired = !covered && requirement.importance === 'REQUIRED'; const Icon = covered ? CheckCircle2 : missingRequired ? AlertCircle : Circle; return <div className="flex items-center gap-2 text-sm" key={requirement.id}><Icon size={15} className={covered ? 'text-aura-success' : missingRequired ? 'text-aura-danger' : 'text-aura-text-muted'} /><span className="flex-1 text-depth">{requirement.label}</span><span className="text-[10px] font-bold uppercase tracking-wide text-aura-text-muted">{covered ? 'Covered' : missingRequired ? 'Required missing' : 'Preferred missing'}</span></div> })}</div><div className="mt-4 border-t border-harbor/10 pt-4"><p className="m-0 text-xs font-semibold text-aura-text-muted">Category balance</p><div className="mt-2 flex flex-wrap gap-2">{Object.entries(categories).map(([category, count]) => <span className="rounded-full bg-frost px-2.5 py-1 text-xs text-harbor" key={category}>{category.toLocaleLowerCase().replaceAll('_', ' ')} · {count}</span>)}</div></div></Card>
}
