import { useState } from 'react'
import type { InterviewQuestionSet } from '../../types/interviewQuestionSet'
import type { InterviewQuestionSetReadiness } from '../../utils/interviewQuestionSetReadiness'
import { formatDateTime } from '../../utils/helpers'
import { Button } from '../ui/Button'
import { Card } from '../ui/Card'
import { Dialog } from '../ui/Dialog'

export function InterviewQuestionApproval({ questionSet, readiness, onApprove, onRegenerate }: { questionSet: InterviewQuestionSet; readiness: InterviewQuestionSetReadiness; onApprove: () => void; onRegenerate: () => void }) {
  const [approveOpen, setApproveOpen] = useState(false)
  const [regenerateOpen, setRegenerateOpen] = useState(false)
  if (questionSet.status === 'APPROVED') return <Card className="border-aura-success/25 bg-aura-success-soft/35 p-5"><p className="m-0 text-[10px] font-bold uppercase tracking-[0.14em] text-aura-success">Interview plan approved</p><h2 className="mb-0 mt-2 text-lg font-semibold text-depth">Ready for the interview</h2><p className="mb-0 mt-2 text-sm text-aura-text-secondary">Approved by {questionSet.approvedBy} on {questionSet.approvedAt ? formatDateTime(questionSet.approvedAt) : '—'}.</p><p className="mb-0 mt-1 text-xs text-aura-text-muted">{readiness.questionCount} approved questions · {readiness.estimatedMinutes} planned minutes</p></Card>
  return <><Card className="p-5"><h2 className="m-0 text-base font-semibold text-depth">Question plan requires review</h2><p className="mb-0 mt-2 text-sm leading-6 text-aura-text-secondary">Confirm that the questions fit the interview duration and cover the role’s required qualifications.</p>{readiness.blockingIssues.length ? <div className="mt-4 rounded-aura-sm bg-aura-danger-soft p-3"><p className="m-0 text-xs font-bold uppercase tracking-wide text-aura-danger">Resolve before approval</p><ul className="mb-0 mt-2 pl-5 text-sm text-aura-danger">{readiness.blockingIssues.map((issue) => <li key={issue}>{issue}</li>)}</ul></div> : null}{readiness.warnings.length ? <ul className="mb-0 mt-4 pl-5 text-xs leading-5 text-aura-warning">{readiness.warnings.map((warning) => <li key={warning}>{warning}</li>)}</ul> : null}<Button className="mt-5 w-full" disabled={!readiness.ready} onClick={() => setApproveOpen(true)}>Approve interview plan</Button><Button className="mt-2 w-full" variant="ghost" onClick={() => setRegenerateOpen(true)}>Regenerate questions</Button></Card><Dialog open={approveOpen} title="Approve interview question plan?" onClose={() => setApproveOpen(false)}><p className="mt-0 text-sm leading-6 text-aura-text-secondary">The approved questions will be used during the interview session. The plan will become read-only.</p><div className="mt-6 flex justify-end gap-2"><Button variant="ghost" onClick={() => setApproveOpen(false)}>Cancel</Button><Button onClick={() => { onApprove(); setApproveOpen(false) }}>Approve plan</Button></div></Dialog><Dialog open={regenerateOpen} title="Regenerate interview questions?" onClose={() => setRegenerateOpen(false)}><p className="mt-0 text-sm leading-6 text-aura-text-secondary">Regenerating will replace the current draft and discard manual edits.</p><div className="mt-6 flex justify-end gap-2"><Button variant="ghost" onClick={() => setRegenerateOpen(false)}>Cancel</Button><Button variant="secondary" onClick={() => { onRegenerate(); setRegenerateOpen(false) }}>Regenerate questions</Button></div></Dialog></>
}
