import type { Application } from '../types/application'; import type { Candidate } from '../types/candidate'; import type { Interview } from '../types/interview'; import type { InterviewQuestionSet } from '../types/interviewQuestionSet'; import type { InterviewSession } from '../types/interviewSession'; import type { InterviewTranscript, InterviewTranscriptSegment } from '../types/interviewTranscript'; import type { Job } from '../types/job'; import { createInterviewTranscriptId, createNextTranscriptSegmentId } from '../utils/interviewPostReviewIds'
export type SimulatedTranscriptInput = { interview: Interview; session: InterviewSession; questionSet: InterviewQuestionSet; candidate: Candidate; application: Application; job: Job; generatedAt: string }
export function generateSimulatedInterviewTranscript(input: SimulatedTranscriptInput): InterviewTranscript {
  const id = createInterviewTranscriptId(input.interview.id); const segments: InterviewTranscriptSegment[] = []; const answers = input.application.answers.map((item) => `${item.label}: ${Array.isArray(item.value) ? item.value.join(', ') : String(item.value)}`).join(' ')
  const add = (speaker: 'INTERVIEWER' | 'CANDIDATE', text: string, questionId: string) => segments.push({ id: createNextTranscriptSegmentId(segments, input.interview.id), transcriptId: id, order: segments.length + 1, speaker, speakerLabel: speaker === 'INTERVIEWER' ? 'Interviewer' : input.candidate.fullName, text, questionId, createdAt: input.generatedAt, updatedAt: input.generatedAt })
  ;[...input.questionSet.questions].sort((a, b) => a.order - b.order).forEach((question) => { const progress = input.session.questionProgress.find((item) => item.questionId === question.id); if (progress?.status !== 'ASKED') return; add('INTERVIEWER', question.text, question.id); const note = progress.interviewerNotes.trim(); add('CANDIDATE', note ? `The interviewer recorded: ${note}` : `I discussed my experience relevant to ${input.job.title}. ${answers.slice(0, 260) || `My background includes ${input.candidate.skills.join(', ')}.`}`, question.id); progress.followUpNotes.forEach((followUp) => { add('INTERVIEWER', followUp, question.id); add('CANDIDATE', 'I provided additional context based on the experience described in my application and interview notes.', question.id) }) })
  const rawText = segments.map((item) => `${item.speaker === 'INTERVIEWER' ? 'Interviewer' : 'Candidate'}: ${item.text}`).join('\n\n')
  return { id, interviewId: input.interview.id, sessionId: input.session.id, source: 'SIMULATED', status: 'DRAFT', rawText, segments, createdAt: input.generatedAt, updatedAt: input.generatedAt }
}
