import { useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { CurrentInterviewQuestion } from '../../components/interviews/CurrentInterviewQuestion'
import { InterviewCandidateContext } from '../../components/interviews/InterviewCandidateContext'
import { InterviewQuestionNavigator } from '../../components/interviews/InterviewQuestionNavigator'
import { InterviewQuestionNotes } from '../../components/interviews/InterviewQuestionNotes'
import { InterviewScreeningContext } from '../../components/interviews/InterviewScreeningContext'
import { InterviewSessionControls } from '../../components/interviews/InterviewSessionControls'
import { InterviewSessionProgress } from '../../components/interviews/InterviewSessionProgress'
import { PageContainer } from '../../components/layout/PageContainer'
import { Badge } from '../../components/ui/Badge'
import { Button } from '../../components/ui/Button'
import { Card } from '../../components/ui/Card'
import { Dialog } from '../../components/ui/Dialog'
import { useDemoStore } from '../../hooks/useDemoStore'
import { useInterviewSessionTimer } from '../../hooks/useInterviewSessionTimer'
import { createInterviewSession } from '../../services/interviewSessionInitialization'
import { selectApprovedInterviewQuestionSet, selectInterviewSessionByInterviewId, selectInterviewSessionProgressSummary } from '../../store/demoSelectors'
import { evaluateInterviewSessionCompletionReadiness } from '../../utils/interviewSessionCompletion'
import { deriveJobRequirements } from '../../utils/jobRequirements'
import { formatInterviewDate, formatInterviewMode, formatInterviewTime } from '../../utils/helpers'

const linkClass = 'inline-flex h-10 items-center justify-center rounded-aura-sm border border-marine/35 bg-white px-4 text-sm font-semibold text-harbor no-underline focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-glacier'
const quietLinkClass = 'inline-flex h-9 items-center justify-center rounded-aura-sm px-2.5 text-sm font-semibold text-harbor no-underline hover:bg-glacier/10 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-glacier'
const primaryLinkClass = 'inline-flex h-9 items-center justify-center rounded-aura-sm bg-harbor px-3.5 text-sm font-semibold text-frost no-underline hover:bg-depth focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-glacier'
export default function InterviewSession() {
  const { interviewId = '' } = useParams(); const { state, dispatch } = useDemoStore(); const [completeOpen, setCompleteOpen] = useState(false); const [generalNotes, setGeneralNotes] = useState('')
  const interview = state.interviews.find((item) => item.id === interviewId); const application = interview ? state.applications.find((item) => item.id === interview.applicationId) : undefined; const candidate = application ? state.candidates.find((item) => item.id === application.candidateId) : undefined; const job = application ? state.jobs.find((item) => item.id === application.jobId) : undefined; const questionSet = selectApprovedInterviewQuestionSet(state, interviewId); const session = selectInterviewSessionByInterviewId(state, interviewId)
  const evaluation = application ? state.evaluations.filter((item) => item.applicationId === application.id && item.evaluationType === 'SCREENING' && item.status === 'COMPLETED').sort((a, b) => b.createdAt.localeCompare(a.createdAt))[0] : undefined; const decision = application ? state.decisions.filter((item) => item.applicationId === application.id).sort((a, b) => b.createdAt.localeCompare(a.createdAt))[0] : undefined
  useEffect(() => { if (interview && questionSet && !session && interview.status === 'SCHEDULED') { const createdAt = new Date().toISOString(); dispatch({ type: 'ADD_INTERVIEW_SESSION', payload: { session: createInterviewSession({ interview, questionSet, createdAt }) } }) } }, [dispatch, interview, questionSet, session])
  useEffect(() => setGeneralNotes(session?.generalNotes ?? ''), [session?.generalNotes, session?.id])
  const timer = useInterviewSessionTimer(session)
  if (!interview || !application || !candidate || !job) return <PageContainer eyebrow="Live interview" title="Interview not found"><Card className="p-8 text-center text-aura-text-secondary">The interview session could not be resolved.</Card></PageContainer>
  if (interview.status === 'CANCELLED') return <PageContainer eyebrow="Live interview" title="This interview has been cancelled"><Link className={linkClass} to={`/interviews/${interview.id}`}>Return to interview</Link></PageContainer>
  if (!questionSet) return <PageContainer eyebrow="Live interview" title="Interview plan approval required" description="Approve the interview question plan before starting the session."><Link className={linkClass} to={`/interviews/${interview.id}/questions`}>Review question plan</Link></PageContainer>
  if (!session) return <PageContainer eyebrow="Live interview" title="Preparing session workspace"><Card className="p-8 text-center text-sm text-aura-text-secondary">Creating the interviewer workspace from the approved question plan.</Card></PageContainer>
  const questions = [...questionSet.questions].sort((a, b) => a.order - b.order); const summary = selectInterviewSessionProgressSummary(session); const currentIndex = questions.findIndex((item) => item.id === session.currentQuestionId); const visibleIndex = currentIndex >= 0 ? currentIndex : 0; const currentQuestion = questions[visibleIndex]; const currentProgress = session.questionProgress.find((item) => item.questionId === currentQuestion?.id); const readiness = evaluateInterviewSessionCompletionReadiness(session); const now = () => new Date().toISOString(); const editable = session.status === 'IN_PROGRESS' || session.status === 'PAUSED'
  const saveGeneral = () => dispatch({ type: 'UPDATE_INTERVIEW_SESSION_GENERAL_NOTES', payload: { sessionId: session.id, notes: generalNotes, updatedAt: now() } })
  function selectQuestion(questionId: string) { dispatch({ type: 'SET_CURRENT_SESSION_QUESTION', payload: { sessionId: session!.id, questionId, changedAt: now() } }) }
  function complete() { saveGeneral(); dispatch({ type: 'COMPLETE_INTERVIEW_SESSION', payload: { sessionId: session!.id, completedAt: now(), activeSecondsSinceResume: timer.captureActiveSeconds() } }); setCompleteOpen(false) }
  if (session.status === 'COMPLETED') {
    const transcript = state.interviewTranscripts.find((item) => item.interviewId === interview.id)
    return <PageContainer title="Interview summary" hideHeader><div className="mx-auto max-w-[1040px]"><header className="mb-5 flex flex-wrap items-start justify-between gap-3"><div><h1 className="m-0 text-[28px] font-bold tracking-[-0.025em] text-depth md:text-[32px]">Interview summary</h1><p className="mb-0 mt-1 text-sm text-aura-text-secondary">{candidate.fullName} · {job.title}</p></div><Link className={quietLinkClass} to={`/interviews/${interview.id}`}>Interview details</Link></header><Card className="p-5 shadow-none md:p-6"><div className="flex items-start justify-between gap-4"><div><p className="m-0 text-sm font-semibold text-depth">{formatInterviewDate(interview.scheduledStart)} · {formatInterviewTime(interview.scheduledStart)}–{formatInterviewTime(interview.scheduledEnd)}</p><p className="mb-0 mt-1 text-xs text-aura-text-muted">{formatInterviewMode(interview.mode ?? 'VIDEO')} · {interview.interviewers.map((person) => person.name).join(', ')}</p></div><Badge tone="success">Completed</Badge></div><dl className="mt-6 flex flex-wrap gap-x-10 gap-y-4"><SummaryFact label="Duration" value={timer.formattedElapsed} /><SummaryFact label="Asked" value={String(summary.asked)} /><SummaryFact label="Skipped" value={String(summary.skipped)} /><SummaryFact label="Not reached" value={String(summary.notAsked + summary.current)} /></dl>{session.completionSummary ? <p className="mb-0 mt-6 max-w-3xl text-sm leading-6 text-aura-text-secondary">{session.completionSummary}</p> : null}<div className="mt-6 flex flex-wrap items-center justify-between gap-3"><Link className={quietLinkClass} to={`/interviews/${interview.id}/questions`}>Question plan</Link><Link className={primaryLinkClass} to={`/interviews/${interview.id}/transcript`}>{transcript ? 'View transcript' : 'Add transcript'}</Link></div></Card></div></PageContainer>
  }
  return <PageContainer eyebrow="Live interview" title="Interview session" description="Follow the approved interview plan, capture evidence, and track question progress in one workspace." actions={<Link className={linkClass} to={`/interviews/${interview.id}`}>Interview details</Link>}>
    <Card className="mb-4 overflow-hidden"><div className="grid gap-px bg-harbor/10 sm:grid-cols-2 xl:grid-cols-5">{[['Candidate', candidate.fullName], ['Applied role', job.title], ['Schedule', `${formatInterviewDate(interview.scheduledStart)} · ${formatInterviewTime(interview.scheduledStart)}`], ['Mode', formatInterviewMode(interview.mode ?? 'VIDEO')], ['Interview team', interview.interviewers.map((person) => person.name).join(', ')]].map(([label, value]) => <div className="bg-white p-4" key={label}><p className="m-0 text-[10px] font-bold uppercase tracking-wide text-aura-text-muted">{label}</p><p className="mb-0 mt-1 text-sm font-semibold text-depth">{value}</p></div>)}</div></Card>
    {session.status === 'NOT_STARTED' ? <Card className="mb-4 border-marine/20 p-5"><h2 className="m-0 text-lg font-semibold text-depth">Ready to begin</h2><p className="mb-0 mt-2 text-sm text-aura-text-secondary">The approved interview plan contains {questions.length} questions and approximately {questions.reduce((sum, question) => sum + question.estimatedMinutes, 0)} minutes of planned discussion.</p><ul className="mb-0 mt-4 grid gap-1 pl-5 text-sm text-harbor"><li>Interview plan approved</li><li>Candidate and role context available</li><li>Interview notes ready</li></ul></Card> : null}
    <div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_22rem]"><main className="grid content-start gap-4">{currentQuestion && currentProgress ? <><CurrentInterviewQuestion question={currentQuestion} progress={currentProgress} requirements={deriveJobRequirements(job)} active={session.status === 'IN_PROGRESS'} hasPrevious={visibleIndex > 0} hasNext={visibleIndex < questions.length - 1} onAsked={() => dispatch({ type: 'MARK_SESSION_QUESTION_ASKED', payload: { sessionId: session.id, questionId: currentQuestion.id, completedAt: now() } })} onSkipped={() => dispatch({ type: 'MARK_SESSION_QUESTION_SKIPPED', payload: { sessionId: session.id, questionId: currentQuestion.id, skippedAt: now() } })} onPrevious={() => selectQuestion(questions[visibleIndex - 1].id)} onNext={() => selectQuestion(questions[visibleIndex + 1].id)} /><InterviewQuestionNotes progress={currentProgress} editable={editable} onSave={(notes) => dispatch({ type: 'UPDATE_SESSION_QUESTION_NOTES', payload: { sessionId: session.id, questionId: currentQuestion.id, notes, updatedAt: now() } })} onAddFollowUp={(followUp) => dispatch({ type: 'ADD_SESSION_FOLLOW_UP', payload: { sessionId: session.id, questionId: currentQuestion.id, followUp, updatedAt: now() } })} onRemoveFollowUp={(followUpIndex) => dispatch({ type: 'REMOVE_SESSION_FOLLOW_UP', payload: { sessionId: session.id, questionId: currentQuestion.id, followUpIndex, updatedAt: now() } })} /><div className="grid gap-4 lg:grid-cols-2"><InterviewCandidateContext candidate={candidate} job={job} /><InterviewScreeningContext evaluation={evaluation} decision={decision} /></div></> : null}</main><aside className="grid content-start gap-4"><Card className="p-5"><InterviewSessionControls interviewId={interview.id} status={session.status} formattedElapsed={timer.formattedElapsed} onStart={() => dispatch({ type: 'START_INTERVIEW_SESSION', payload: { sessionId: session.id, startedAt: now() } })} onPause={() => { saveGeneral(); dispatch({ type: 'PAUSE_INTERVIEW_SESSION', payload: { sessionId: session.id, pausedAt: now(), activeSecondsSinceResume: timer.captureActiveSeconds() } }) }} onResume={() => dispatch({ type: 'RESUME_INTERVIEW_SESSION', payload: { sessionId: session.id, resumedAt: now() } })} onComplete={() => setCompleteOpen(true)} /></Card><Card className="p-5"><InterviewSessionProgress summary={summary} /></Card><Card className="p-5"><InterviewQuestionNavigator session={session} questions={questions} onSelect={selectQuestion} /></Card><Card className="p-5"><label className="text-sm font-semibold text-depth">General interview notes<textarea className="mt-2 min-h-28 w-full resize-y rounded-aura-sm border border-harbor/20 px-3 py-2 text-sm text-depth focus:outline-none focus:ring-2 focus:ring-glacier disabled:bg-frost" disabled={!editable} maxLength={10000} value={generalNotes} onChange={(event) => setGeneralNotes(event.target.value)} onBlur={saveGeneral} /></label></Card></aside></div>
    <Dialog open={completeOpen} title="End interview session?" onClose={() => setCompleteOpen(false)}><p className="mt-0 text-sm leading-6 text-aura-text-secondary">The live session will end and the interview record will become read-only. Transcript and evaluation will be handled in the next workflow stage.</p><dl className="mt-4 grid grid-cols-2 gap-3 text-sm"><div><dt className="text-aura-text-muted">Asked</dt><dd className="m-0 font-semibold text-depth">{readiness.askedCount}</dd></div><div><dt className="text-aura-text-muted">Skipped</dt><dd className="m-0 font-semibold text-depth">{readiness.skippedCount}</dd></div><div><dt className="text-aura-text-muted">Not reached</dt><dd className="m-0 font-semibold text-depth">{readiness.remainingCount}</dd></div><div><dt className="text-aura-text-muted">Active time</dt><dd className="m-0 font-semibold text-depth">{timer.formattedElapsed}</dd></div></dl>{readiness.warnings.map((warning) => <p className="mb-0 mt-4 rounded-aura-sm bg-aura-warning-soft p-3 text-sm text-aura-warning" key={warning}>{warning}</p>)}<div className="mt-6 flex justify-end gap-2"><Button variant="ghost" onClick={() => setCompleteOpen(false)}>Cancel</Button><Button disabled={!readiness.ready} onClick={complete}>End session</Button></div></Dialog>
  </PageContainer>
}

function SummaryFact({ label, value }: { label: string; value: string }) {
  return <div><dt className="text-[10px] font-bold uppercase tracking-wide text-aura-text-muted">{label}</dt><dd className="mb-0 mt-1 text-lg font-semibold text-depth">{value}</dd></div>
}
