"""add automatic ai screening workflow

Revision ID: 0e5f4d649ee4
Revises: 192639fe236a
Create Date: 2026-07-18 07:18:54.482663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0e5f4d649ee4'
down_revision: Union[str, Sequence[str], None] = '192639fe236a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('phone', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidates_email'), 'candidates', ['email'], unique=True)
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('department', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('is_accepting_applications', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('cv_required', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('github_repository_required', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_table('applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('submission_status', sa.String(length=40), nullable=False),
    sa.Column('stage', sa.String(length=40), nullable=False),
    sa.Column('github_repository_url', sa.String(length=500), nullable=True),
    sa.Column('cv_original_filename', sa.String(length=255), nullable=True),
    sa.Column('cv_storage_path', sa.String(length=500), nullable=True),
    sa.Column('cv_mime_type', sa.String(length=200), nullable=True),
    sa.Column('cv_extracted_text', sa.Text(), nullable=True),
    sa.Column('cv_extraction_status', sa.String(length=40), nullable=False),
    sa.Column('submission_idempotency_key', sa.String(length=200), nullable=True),
    sa.Column('candidate_status_token_hash', sa.String(length=128), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_idempotency_key')
    )
    op.create_index(op.f('ix_applications_candidate_id'), 'applications', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_applications_job_id'), 'applications', ['job_id'], unique=False)
    op.create_index(op.f('ix_applications_stage'), 'applications', ['stage'], unique=False)
    op.create_index(op.f('ix_applications_submission_status'), 'applications', ['submission_status'], unique=False)
    op.create_table('job_requirements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'code', name='uq_job_requirements_job_code')
    )
    op.create_index(op.f('ix_job_requirements_job_id'), 'job_requirements', ['job_id'], unique=False)
    op.create_table('screening_rubrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('minimum_assessed_coverage', sa.Integer(), nullable=False),
    sa.Column('advance_threshold', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_screening_rubrics_job_id'), 'screening_rubrics', ['job_id'], unique=False)
    op.create_index(op.f('ix_screening_rubrics_status'), 'screening_rubrics', ['status'], unique=False)
    op.create_table('application_answers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('question_key', sa.String(length=160), nullable=False),
    sa.Column('question_label', sa.String(length=300), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=False),
    sa.Column('linked_requirement_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_answers_application_id'), 'application_answers', ['application_id'], unique=False)
    op.create_table('github_repository_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('repository_url', sa.String(length=500), nullable=False),
    sa.Column('owner', sa.String(length=120), nullable=False),
    sa.Column('repository_name', sa.String(length=160), nullable=False),
    sa.Column('default_branch', sa.String(length=160), nullable=True),
    sa.Column('repository_description', sa.Text(), nullable=True),
    sa.Column('primary_language', sa.String(length=120), nullable=True),
    sa.Column('languages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('repository_size', sa.Integer(), nullable=True),
    sa.Column('is_fork', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('readme_present', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('tests_detected', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('ci_detected', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('docker_detected', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('dependency_files', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('files_reviewed_count', sa.Integer(), nullable=False),
    sa.Column('total_characters_analyzed', sa.Integer(), nullable=False),
    sa.Column('analysis_status', sa.String(length=40), nullable=False),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_github_repository_analyses_application_id'), 'github_repository_analyses', ['application_id'], unique=False)
    op.create_table('screening_rubric_criteria',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rubric_id', sa.UUID(), nullable=False),
    sa.Column('criterion_key', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('must_have', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('minimum_rating', sa.Integer(), nullable=True),
    sa.Column('linked_requirement_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rubric_id'], ['screening_rubrics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rubric_id', 'criterion_key', name='uq_screening_rubric_criteria_key')
    )
    op.create_index(op.f('ix_screening_rubric_criteria_rubric_id'), 'screening_rubric_criteria', ['rubric_id'], unique=False)
    op.create_table('screening_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('rubric_id', sa.UUID(), nullable=False),
    sa.Column('rubric_version', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('prompt_version', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('assessed_coverage', sa.Integer(), nullable=True),
    sa.Column('weighted_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('recommendation', sa.String(length=60), nullable=True),
    sa.Column('overall_confidence', sa.String(length=20), nullable=True),
    sa.Column('overall_strengths', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('overall_concerns', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('verification_questions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('unresolved_requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('data_quality_warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('safe_error_detail', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rubric_id'], ['screening_rubrics.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_screening_runs_application_id'), 'screening_runs', ['application_id'], unique=False)
    op.create_index(op.f('ix_screening_runs_rubric_id'), 'screening_runs', ['rubric_id'], unique=False)
    op.create_index(op.f('ix_screening_runs_status'), 'screening_runs', ['status'], unique=False)
    op.create_index('uq_screening_runs_active_application', 'screening_runs', ['application_id'], unique=True, postgresql_where=sa.text("status in ('QUEUED', 'PROCESSING')"))
    op.create_table('github_code_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_analysis_id', sa.UUID(), nullable=False),
    sa.Column('evidence_id', sa.String(length=300), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('language', sa.String(length=120), nullable=True),
    sa.Column('line_start', sa.Integer(), nullable=True),
    sa.Column('line_end', sa.Integer(), nullable=True),
    sa.Column('evidence_type', sa.String(length=80), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('content_excerpt', sa.Text(), nullable=False),
    sa.Column('related_criterion_keys', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repository_analysis_id'], ['github_repository_analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_github_code_evidence_evidence_id'), 'github_code_evidence', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_github_code_evidence_repository_analysis_id'), 'github_code_evidence', ['repository_analysis_id'], unique=False)
    op.create_table('human_screening_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('screening_run_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('reviewer_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['screening_run_id'], ['screening_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_human_screening_reviews_application_id'), 'human_screening_reviews', ['application_id'], unique=False)
    op.create_index(op.f('ix_human_screening_reviews_reviewer_id'), 'human_screening_reviews', ['reviewer_id'], unique=False)
    op.create_index(op.f('ix_human_screening_reviews_screening_run_id'), 'human_screening_reviews', ['screening_run_id'], unique=False)
    op.create_table('screening_criterion_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('screening_run_id', sa.UUID(), nullable=False),
    sa.Column('criterion_key', sa.String(length=100), nullable=False),
    sa.Column('suggested_rating', sa.Integer(), nullable=True),
    sa.Column('normalized_score', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('weighted_contribution', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('evidence_summary', sa.Text(), nullable=False),
    sa.Column('strengths', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('concerns', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('missing_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('requires_human_review', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['screening_run_id'], ['screening_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_screening_criterion_results_criterion_key'), 'screening_criterion_results', ['criterion_key'], unique=False)
    op.create_index(op.f('ix_screening_criterion_results_screening_run_id'), 'screening_criterion_results', ['screening_run_id'], unique=False)
    op.create_table('screening_evidence_references',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('screening_run_id', sa.UUID(), nullable=False),
    sa.Column('criterion_key', sa.String(length=100), nullable=False),
    sa.Column('evidence_id', sa.String(length=300), nullable=False),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('source_record_id', sa.UUID(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['screening_run_id'], ['screening_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_screening_evidence_references_screening_run_id'), 'screening_evidence_references', ['screening_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_screening_evidence_references_screening_run_id'), table_name='screening_evidence_references')
    op.drop_table('screening_evidence_references')
    op.drop_index(op.f('ix_screening_criterion_results_screening_run_id'), table_name='screening_criterion_results')
    op.drop_index(op.f('ix_screening_criterion_results_criterion_key'), table_name='screening_criterion_results')
    op.drop_table('screening_criterion_results')
    op.drop_index(op.f('ix_human_screening_reviews_screening_run_id'), table_name='human_screening_reviews')
    op.drop_index(op.f('ix_human_screening_reviews_reviewer_id'), table_name='human_screening_reviews')
    op.drop_index(op.f('ix_human_screening_reviews_application_id'), table_name='human_screening_reviews')
    op.drop_table('human_screening_reviews')
    op.drop_index(op.f('ix_github_code_evidence_repository_analysis_id'), table_name='github_code_evidence')
    op.drop_index(op.f('ix_github_code_evidence_evidence_id'), table_name='github_code_evidence')
    op.drop_table('github_code_evidence')
    op.drop_index('uq_screening_runs_active_application', table_name='screening_runs', postgresql_where=sa.text("status in ('QUEUED', 'PROCESSING')"))
    op.drop_index(op.f('ix_screening_runs_status'), table_name='screening_runs')
    op.drop_index(op.f('ix_screening_runs_rubric_id'), table_name='screening_runs')
    op.drop_index(op.f('ix_screening_runs_application_id'), table_name='screening_runs')
    op.drop_table('screening_runs')
    op.drop_index(op.f('ix_screening_rubric_criteria_rubric_id'), table_name='screening_rubric_criteria')
    op.drop_table('screening_rubric_criteria')
    op.drop_index(op.f('ix_github_repository_analyses_application_id'), table_name='github_repository_analyses')
    op.drop_table('github_repository_analyses')
    op.drop_index(op.f('ix_application_answers_application_id'), table_name='application_answers')
    op.drop_table('application_answers')
    op.drop_index(op.f('ix_screening_rubrics_status'), table_name='screening_rubrics')
    op.drop_index(op.f('ix_screening_rubrics_job_id'), table_name='screening_rubrics')
    op.drop_table('screening_rubrics')
    op.drop_index(op.f('ix_job_requirements_job_id'), table_name='job_requirements')
    op.drop_table('job_requirements')
    op.drop_index(op.f('ix_applications_submission_status'), table_name='applications')
    op.drop_index(op.f('ix_applications_stage'), table_name='applications')
    op.drop_index(op.f('ix_applications_job_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_candidate_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_candidates_email'), table_name='candidates')
    op.drop_table('candidates')
    # ### end Alembic commands ###
