import { useState } from 'react'
import { Link, useLocation, useParams } from 'react-router-dom'
import { CompetencyAssessmentList } from '../components/evaluation/CompetencyAssessmentList'
import { EvaluationChallengeDialog } from '../components/evaluation/EvaluationChallengeDialog'
import { EvaluationChallengeList } from '../components/evaluation/EvaluationChallengeList'
import { EvaluationDataQuality } from '../components/evaluation/EvaluationDataQuality'
import { HumanFinalDecision, type FinalDecisionDraft } from '../components/evaluation/HumanFinalDecision'
import { MustHaveGateSummary } from '../components/evaluation/MustHaveGateSummary'
import { QuestionAssessmentList } from '../components/evaluation/QuestionAssessmentList'
import { SystemRecommendationCard } from '../components/evaluation/SystemRecommendationCard'
import { SystemScoreSummary } from '../components/evaluation/SystemScoreSummary'
import { PageContainer } from '../components/layout/PageContainer'
import { Badge } from '../components/ui/Badge'
import { Button } from '../components/ui/Button'
import { Card } from '../components/ui/Card'
import { Dialog } from '../components/ui/Dialog'
import { useAuth } from '../hooks/useAuth'
import { useDemoStore } from '../hooks/useDemoStore'
import { generateFinalEvaluation } from '../services/finalEvaluationGeneration'
import { selectEvaluationChallengesByEvaluationId, selectFinalEvaluationViewModel, selectFinalEvaluationsByCandidateId } from '../store/demoSelectors'
import type { EvaluationChallengeReason } from '../types/evaluationChallenge'
import type { InterviewQuestionAssessment } from '../types/interviewQuestionAssessment'
import { evaluateFinalEvaluationReadiness } from '../utils/finalEvaluationReadiness'
import { createEvaluationChallengeId } from '../utils/finalEvaluationIds'
import { finalEvaluationSourcesChanged } from '../utils/finalEvaluationSourceFingerprint'

const linkClass = 'inline-flex h-10 items-center justify-center rounded-aura-sm border border-marine/30 bg-white px-4 text-sm font-semibold text-harbor no-underline focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-glacier'
function SectionTitle({ children, note }: { children: string; note: string }) { return <div className="mb-3"><h2 className="m-0 text-lg font-semibold text-depth">{children}</h2><p className="mb-0 mt-1 text-xs text-aura-text-muted">{note}</p></div> }

export default function FinalEvaluation() {
  const { candidateId = '' } = useParams(); const location = useLocation(); const { state, dispatch } = useDemoStore(); const { currentUser } = useAuth(); const [challengeAssessment, setChallengeAssessment] = useState<InterviewQuestionAssessment>(); const [recalculateOpen, setRecalculateOpen] = useState(false); const fastForwardError = (location.state as { demoFastForwardError?: string } | null)?.demoFastForwardError
  const view = selectFinalEvaluationViewModel(state, candidateId); const versions = selectFinalEvaluationsByCandidateId(state, candidateId); const candidate = state.candidates.find((item) => item.id === candidateId)
  if (!candidate) return <PageContainer eyebrow="Final evaluation" title="Candidate not found"><Card className="p-8 text-sm text-aura-text-secondary">The requested candidate record could not be resolved.</Card></PageContainer>
  if (!view) { const application = state.applications.find((item) => item.candidateId === candidateId); const interview = application ? state.interviews.find((item) => item.applicationId === application.id) : undefined; const analysis = interview ? state.interviewAnalyses.find((item) => item.interviewId === interview.id) : undefined; const preparationError = fastForwardError ?? analysis?.generationError; return <PageContainer eyebrow="Final evaluation" title={preparationError ? 'Final evaluation needs attention' : analysis?.status !== 'APPROVED' ? 'Interview analysis approval required' : 'Final evaluation preparing'} description={preparationError ?? (analysis?.status !== 'APPROVED' ? 'Approve the interview evidence analysis before preparing the final evaluation.' : 'AURA is preparing standardized evidence scoring from the approved interview evidence.')} actions={interview ? <Link className={linkClass} to={`/interviews/${interview.id}/analysis`}>Review interview analysis</Link> : undefined}><Card className={`p-6 text-sm ${preparationError ? 'border-aura-danger/25 bg-aura-danger-soft text-aura-danger' : 'text-aura-text-secondary'}`} role={preparationError ? 'alert' : undefined}>{preparationError ?? (interview ? 'Required evaluation references are being resolved.' : 'A completed interview is required before final evaluation.')}</Card></PageContainer> }
  const { evaluation, application, job, interview, analysis, rubric } = view; const transcript = state.interviewTranscripts.find((item) => item.interviewId === interview.id); const set = state.interviewQuestionSets.find((item) => item.interviewId === interview.id && item.status === 'APPROVED'); const session = state.interviewSessions.find((item) => item.interviewId === interview.id && item.status === 'COMPLETED'); const challenges = selectEvaluationChallengesByEvaluationId(state, evaluation.id); const readiness = evaluateFinalEvaluationReadiness(evaluation, challenges)
  if (evaluation.status === 'GENERATION_FAILED') return <PageContainer eyebrow="Final evaluation" title="Final evaluation needs attention" description={evaluation.generationError ?? fastForwardError ?? 'AURA could not prepare the scoring workspace.'} actions={<Link className={linkClass} to={`/interviews/${interview.id}/analysis`}>Review approved analysis</Link>}><Card className="border-aura-danger/25 bg-aura-danger-soft p-6" role="alert"><p className="m-0 text-sm font-semibold text-aura-danger">The simulated transcript and analysis remain approved.</p><p className="mb-0 mt-2 text-sm text-aura-danger">Review the published scoring rubric and approved interview evidence, then retry evaluation preparation.</p></Card></PageContainer>
  if (!transcript || !set || !session) return <PageContainer eyebrow="Final evaluation" title="Final evaluation needs attention" description="AURA cannot calculate a reliable evidence score until the missing evaluation data is resolved."><Link className={linkClass} to={`/interviews/${interview.id}`}>Review interview record</Link></PageContainer>
  function openChallenge(reason: EvaluationChallengeReason, explanation: string) { if (!challengeAssessment) return; const now = new Date().toISOString(); const competencyIds = evaluation.competencyAssessments.filter((item) => challengeAssessment.competencyKeys.includes(item.competencyKey)).map((item) => item.id); dispatch({ type: 'ADD_EVALUATION_CHALLENGE', payload: { actorRole: currentUser.role, challenge: { id: createEvaluationChallengeId(state.evaluationChallenges, evaluation.id), finalEvaluationId: evaluation.id, reason, explanation, questionAssessmentIds: [challengeAssessment.id], competencyAssessmentIds: competencyIds, transcriptSegmentIds: [...challengeAssessment.transcriptSegmentIds], evidenceIds: [...challengeAssessment.evidenceIds], status: 'OPEN', createdBy: currentUser.name, createdAt: now } } }); setChallengeAssessment(undefined) }
  function recordDecision(draft: FinalDecisionDraft) { dispatch({ type: 'RECORD_HUMAN_FINAL_DECISION', payload: { finalEvaluationId: evaluation.id, ...draft, decidedBy: currentUser.name, decidedByRole: currentUser.role, decidedAt: new Date().toISOString() } }) }
  function recalculate() { if (!set || !transcript || !session) return; const generatedAt = new Date().toISOString(); const result = generateFinalEvaluation({ candidateId, applicationId: application.id, jobId: job.id, interviewId: interview.id, analysisId: analysis.id, rubric, questions: set.questions, answerSegments: transcript.segments.filter((item) => item.speaker === 'CANDIDATE').map((item) => ({ id: item.id, questionId: item.questionId, text: item.text })), evidence: analysis.evidence, analysis, transcript, sessionProgress: session.questionProgress, existingEvaluations: state.finalEvaluations, generatedAt }); dispatch({ type: 'ADD_RECALCULATED_FINAL_EVALUATION', payload: { previousEvaluationId: evaluation.id, evaluation: result.finalEvaluation } }); setRecalculateOpen(false) }
  const sourcesChanged = finalEvaluationSourcesChanged(evaluation, transcript, analysis)
  const canRecalculate = evaluation.status !== 'DECIDED' && sourcesChanged
  return <PageContainer eyebrow="Final evaluation" title="Review system evidence scoring" description="Review question-level evidence, competency scores, and the system recommendation before recording the authorized human decision." actions={<Link className={linkClass} to={`/candidates/${candidate.id}`}>Back to candidate</Link>}>
    <Card className="mb-4 p-4"><div className="flex flex-wrap items-center gap-3"><strong className="text-depth">{candidate.fullName}</strong><span className="text-sm text-aura-text-secondary">{job.title}</span><Badge tone={evaluation.status === 'DECIDED' ? 'success' : 'accent'}>{evaluation.status.replaceAll('_', ' ').toLocaleLowerCase()}</Badge><span className="text-xs text-aura-text-muted">Published rubric v{evaluation.rubricVersion} · Evaluation v{evaluation.version}</span></div><p className="mb-0 mt-3 text-xs text-aura-text-muted">Standardized evidence scoring is designed to reduce inconsistent human judgment. It does not eliminate bias and does not make the final hiring decision.</p></Card>
    {sourcesChanged ? <Card className="mb-4 border-aura-warning/35 bg-aura-warning-soft p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="m-0 text-sm font-semibold text-depth">The transcript or evidence mappings changed after this evaluation was generated.</p><p className="mb-0 mt-1 text-xs text-aura-text-secondary">Create a new evaluation version to score the corrected evidence. Evaluation v{evaluation.version} remains unchanged for audit.</p></div>{canRecalculate ? <Button variant="secondary" onClick={() => setRecalculateOpen(true)}>Recalculate evaluation</Button> : null}</div></Card> : null}
    <div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_23rem]"><main className="grid content-start gap-6"><section><SectionTitle note="Competency ratings aggregate assessed question evidence using published weights.">Competency assessments</SectionTitle><CompetencyAssessmentList evaluation={evaluation} transcriptSegments={transcript.segments} rubric={rubric} evidence={analysis.evidence} /></section><MustHaveGateSummary evaluation={evaluation} /><section><SectionTitle note="Every numeric rating remains traceable to an answer, approved evidence, and behavioral anchor.">Question assessments</SectionTitle><QuestionAssessmentList assessments={evaluation.questionAssessments} questions={set.questions} segments={transcript.segments} onChallenge={setChallengeAssessment} /></section><section><SectionTitle note="Challenges document evidence or mapping problems without editing the locked score.">Evidence challenges</SectionTitle><EvaluationChallengeList challenges={challenges} actorRole={currentUser.role} onResolve={(challengeId) => dispatch({ type: 'RESOLVE_EVALUATION_CHALLENGE', payload: { challengeId, resolutionNote: 'The underlying transcript or evidence mapping was corrected and reviewed.', resolvedAt: new Date().toISOString(), actorRole: currentUser.role } })} onDismiss={(challengeId) => dispatch({ type: 'DISMISS_EVALUATION_CHALLENGE', payload: { challengeId, resolutionNote: 'The challenge was reviewed and did not require an evidence correction.', resolvedAt: new Date().toISOString(), actorRole: currentUser.role } })} /></section>{versions.length > 1 ? <Card className="p-5"><h2 className="m-0 text-base font-semibold text-depth">Evaluation version history</h2><div className="mt-3 grid gap-2">{versions.map((item) => <div className="flex justify-between rounded-aura-sm bg-frost p-3 text-sm" key={item.id}><span>Version {item.version} · {item.status.replaceAll('_', ' ').toLocaleLowerCase()}</span><span className="text-aura-text-muted">{item.weightedEvidenceScore === undefined ? 'Score unavailable' : `${item.weightedEvidenceScore}/100`}</span></div>)}</div></Card> : null}</main><aside className="grid content-start gap-4 xl:sticky xl:top-4"><SystemScoreSummary evaluation={evaluation} /><EvaluationDataQuality evaluation={evaluation} challenges={challenges} /><SystemRecommendationCard evaluation={evaluation} /><Card className="p-5"><h2 className="m-0 text-base font-semibold text-depth">Decision readiness</h2>{readiness.blockingIssues.length ? readiness.blockingIssues.map((item) => <p className="mb-0 mt-2 text-xs leading-5 text-aura-warning" key={item}>{item}</p>) : <p className="mb-0 mt-2 text-sm font-semibold text-aura-success">Evidence trail is ready for an authorized decision.</p>}{readiness.warnings.map((item) => <p className="mb-0 mt-2 text-xs text-aura-text-muted" key={item}>{item}</p>)}</Card><HumanFinalDecision evaluation={evaluation} actor={currentUser} ready={readiness.readyForDecision} onRecord={recordDecision} /></aside></div>
    <EvaluationChallengeDialog open={Boolean(challengeAssessment)} assessment={challengeAssessment} onClose={() => setChallengeAssessment(undefined)} onSubmit={openChallenge} />
    <Dialog open={recalculateOpen} title="Recalculate system evaluation?" onClose={() => setRecalculateOpen(false)}><p className="mt-0 text-sm leading-6 text-aura-text-secondary">A new evaluation version will be created from the corrected transcript, evidence, and published rubric. The previous version remains available for audit.</p><div className="mt-6 flex justify-end gap-2"><Button variant="ghost" onClick={() => setRecalculateOpen(false)}>Cancel</Button><Button onClick={recalculate}>Recalculate evaluation</Button></div></Dialog>
  </PageContainer>
}
