import { generateFinalEvaluation } from '../services/finalEvaluationGeneration'
import type { InterviewAnalysis } from '../types/interviewAnalysis'
import type { InterviewEvidence } from '../types/interviewEvidence'
import type { InterviewQuestion } from '../types/interviewQuestion'
import type { InterviewQuestionSet } from '../types/interviewQuestionSet'
import type { InterviewSession } from '../types/interviewSession'
import type { InterviewTranscript } from '../types/interviewTranscript'
import { createInitialDemoState } from '../store/demoInitialState'
import type { DemoState } from '../store/demoStateTypes'
import { deriveJobRequirements } from './jobRequirements'
import { derivePublishedInterviewScoringRubric } from './interviewScoringRubric'

export function createFinalEvaluationValidationFixture() {
  const initial = createInitialDemoState(); const application = initial.applications[0]; const candidate = initial.candidates.find((item) => item.id === application.candidateId)!; const job = initial.jobs.find((item) => item.id === application.jobId)!; const interviewSeed = initial.interviews.find((item) => item.applicationId === application.id) ?? initial.interviews[0]; const sourceRubric = initial.rubrics.find((item) => item.jobId === job.id && item.status === 'PUBLISHED')!; const stamp = '2026-07-17T04:00:00.000Z'; const interview = { ...interviewSeed, applicationId: application.id, status: 'COMPLETED' as const, updatedAt: stamp }
  const texts = ['I enjoy learning and this answer is unrelated to the role.', 'I worked on a project with the team but cannot recall my actions or outcome.', 'I implemented React API testing in a production project and owned the delivery.', 'I owned and implemented a production React API redesign because of constraints, evaluated a trade-off, and reduced errors as the result.', 'I led a complex production redesign, considered an alternative under constraints, reduced incidents by 30 percent, and learned what I would change next time.']
  const questions: InterviewQuestion[] = sourceRubric.criteria.map((criterion, index) => ({ id: `validation-question-${index + 1}`, interviewId: interview.id, text: `Provide evidence for ${criterion.name}.`, category: index === 0 ? 'TECHNICAL' : 'EXPERIENCE', source: 'SYSTEM_GENERATED', priority: index === 4 ? 'OPTIONAL' : 'CORE', status: 'APPROVED', estimatedMinutes: 5, order: index + 1, requirementIds: [], criterionKeys: [criterion.key], evidenceReferences: [], createdAt: stamp, updatedAt: stamp }))
  const set: InterviewQuestionSet = { id: `question-set-${interview.id}-validation`, interviewId: interview.id, version: 1, status: 'APPROVED', questions, createdAt: stamp, updatedAt: stamp, approvedAt: stamp, approvedBy: 'Recruitment Team' }
  const transcriptId = `transcript-${interview.id}`; const segments = questions.map((question, index) => ({ id: `${transcriptId}-segment-${String(index + 1).padStart(3, '0')}`, transcriptId, order: index + 1, speaker: 'CANDIDATE' as const, text: texts[index], questionId: question.id, createdAt: stamp, updatedAt: stamp })); const transcript: InterviewTranscript = { id: transcriptId, interviewId: interview.id, sessionId: `session-${interview.id}`, source: 'MANUAL', status: 'APPROVED', rawText: texts.join('\n'), segments, createdAt: stamp, updatedAt: stamp, approvedAt: stamp, approvedBy: 'Recruitment Team' }
  const session: InterviewSession = { id: transcript.sessionId, interviewId: interview.id, questionSetId: set.id, status: 'COMPLETED', questionProgress: questions.map((question) => ({ questionId: question.id, status: 'ASKED', interviewerNotes: '', followUpNotes: [] })), startedAt: stamp, completedAt: stamp, accumulatedActiveSeconds: 1800, generalNotes: '', createdAt: stamp, updatedAt: stamp }
  const evidence: InterviewEvidence[] = questions.slice(2).map((question, index) => ({ id: `validation-evidence-${index + 1}`, analysisId: `analysis-${interview.id}`, type: index === 0 ? 'TECHNICAL_SKILL' : 'IMPACT', strength: index === 0 ? 'MODERATE' : 'STRONG', title: `Evidence ${index + 1}`, summary: texts[index + 2], transcriptSegmentIds: [segments[index + 2].id], questionIds: [question.id], requirementIds: [], criterionKeys: [...question.criterionKeys], createdAt: stamp, updatedAt: stamp })); const analysis: InterviewAnalysis = { id: `analysis-${interview.id}`, interviewId: interview.id, transcriptId, version: 1, status: 'APPROVED', evidence, strengths: [], concerns: [], missingEvidence: [], interviewerSummary: 'Approved interview evidence.', createdAt: stamp, updatedAt: stamp, approvedAt: stamp, approvedBy: 'Recruitment Team' }
  const rubric = derivePublishedInterviewScoringRubric(sourceRubric, deriveJobRequirements(job), questions)
  const generated = generateFinalEvaluation({ candidateId: candidate.id, applicationId: application.id, jobId: job.id, interviewId: interview.id, analysisId: analysis.id, rubric, questions, answerSegments: segments.map((item) => ({ id: item.id, questionId: item.questionId, text: item.text })), evidence, analysis, transcript, sessionProgress: session.questionProgress, existingEvaluations: [], generatedAt: stamp }).finalEvaluation
  const state: DemoState = { ...initial, interviews: initial.interviews.map((item) => item.id === interview.id ? interview : item), interviewQuestionSets: [set], interviewSessions: [session], interviewTranscripts: [transcript], interviewAnalyses: [analysis] }
  return { initial, state, application, candidate, job, interview, sourceRubric, rubric, set, session, transcript, analysis, evidence, evaluation: generated, stamp }
}
