import { generateFinalEvaluation } from '../services/finalEvaluationGeneration'
import { demoReducer } from '../store/demoReducer'
import { selectCandidateTimeline, selectFinalDecisionDashboardSummary, selectFinalEvaluationPreparationStatus } from '../store/demoSelectors'
import type { HumanFinalDecision } from '../types/finalEvaluation'
import { normalizePersistedDemoState } from '../store/demoPersistence'
import { createEvaluationChallengeId } from './finalEvaluationIds'
import { createFinalEvaluationValidationFixture } from './finalEvaluationValidationFixture'
import { validateDemoFinalDecision } from './demoFinalDecisionValidation'

export type FinalDecisionValidationResult = { valid: boolean; errors: string[] }
export function validateFinalDecisionDomain(): FinalDecisionValidationResult {
  const errors: string[] = [...validateDemoFinalDecision().errors]; const fixture = createFinalEvaluationValidationFixture(); const ready = { ...fixture.evaluation, status: 'READY_FOR_DECISION' as const, dataQualityIssues: [], assessedWeightPercent: 100, overallConfidence: 'MEDIUM' as const, systemRecommendation: 'DO_NOT_ADVANCE' as const, systemRecommendationRationale: 'A required published gate was assessed below its minimum.' }
  const addReady = () => demoReducer(fixture.state, { type: 'ADD_FINAL_EVALUATION', payload: { evaluation: ready } })
  const added = addReady(); if (added.finalEvaluations.length !== 1 || added.finalEvaluations[0].rubricVersion !== fixture.rubric.version) errors.push('Approved analysis did not produce a versioned final evaluation.'); if (added.applications.find((item) => item.id === fixture.application.id)?.currentStage !== 'FINAL_REVIEW') errors.push('Final evaluation generation did not preserve FINAL_REVIEW.')
  const draftAnalysis = { ...fixture.analysis, status: 'DRAFT' as const }; let draftFailed = false; try { generateFinalEvaluation({ candidateId: fixture.candidate.id, applicationId: fixture.application.id, jobId: fixture.job.id, interviewId: fixture.interview.id, analysisId: draftAnalysis.id, rubric: fixture.rubric, questions: fixture.set.questions, answerSegments: fixture.transcript.segments.map((item) => ({ id: item.id, questionId: item.questionId, text: item.text })), evidence: fixture.evidence, analysis: draftAnalysis, sessionProgress: fixture.session.questionProgress, existingEvaluations: [], generatedAt: fixture.stamp }) } catch { draftFailed = true } if (!draftFailed) errors.push('Draft analysis generated a final evaluation.')
  if (demoReducer(added, { type: 'ADD_FINAL_EVALUATION', payload: { evaluation: ready } }) !== added) errors.push('Duplicate evaluation was not prevented.')
  const decisionPayload = (decision: HumanFinalDecision, role: 'INTERVIEWER' | 'RECRUITER' | 'HIRING_MANAGER', reason = 'The decision reflects the published job requirements and reviewed interview evidence.') => ({ finalEvaluationId: ready.id, decision, decisionReason: reason, decidedBy: 'Validation User', decidedByRole: role, decidedAt: '2026-07-17T05:00:00.000Z' })
  if (demoReducer(added, { type: 'RECORD_HUMAN_FINAL_DECISION', payload: decisionPayload('REJECTED', 'INTERVIEWER') }) !== added) errors.push('Interviewer recorded a final decision.')
  if (demoReducer(added, { type: 'RECORD_HUMAN_FINAL_DECISION', payload: decisionPayload('REJECTED', 'RECRUITER') }) !== added) errors.push('Recruiter without authority recorded a final decision.')
  if (demoReducer(added, { type: 'RECORD_HUMAN_FINAL_DECISION', payload: decisionPayload('REJECTED', 'HIRING_MANAGER', 'Too short') }) !== added) errors.push('Invalid short decision reason was accepted.')
  const rejected = demoReducer(added, { type: 'RECORD_HUMAN_FINAL_DECISION', payload: decisionPayload('REJECTED', 'HIRING_MANAGER') }); if (rejected.finalEvaluations[0].status !== 'DECIDED' || rejected.finalEvaluations[0].humanDecision !== 'REJECTED' || rejected.applications.find((item) => item.id === fixture.application.id)?.currentStage !== 'REJECTED') errors.push('Hiring manager could not record an aligned rejection stage.')
  const alignedScore = rejected.finalEvaluations[0].weightedEvidenceScore; if (alignedScore !== ready.weightedEvidenceScore || rejected.finalEvaluations[0].systemRecommendation !== ready.systemRecommendation) errors.push('Human decision changed locked system output.')
  if (demoReducer(rejected, { type: 'RECORD_HUMAN_FINAL_DECISION', payload: decisionPayload('REJECTED', 'HIRING_MANAGER') }) !== rejected) errors.push('Duplicate decision was not prevented.')
  const differingWithoutReason = demoReducer(added, { type: 'RECORD_HUMAN_FINAL_DECISION', payload: decisionPayload('SELECTED', 'HIRING_MANAGER') }); if (differingWithoutReason !== added) errors.push('Differing decision was accepted without disagreement documentation.')
  const selected = demoReducer(added, { type: 'RECORD_HUMAN_FINAL_DECISION', payload: { ...decisionPayload('SELECTED', 'HIRING_MANAGER'), disagreementReason: 'ADDITIONAL_VERIFIED_INFORMATION', disagreementExplanation: 'Additional verified production evidence directly satisfies the published must-have requirement.' } }); if (selected.finalEvaluations[0].humanDecision !== 'SELECTED' || !selected.finalEvaluations[0].differsFromSystem || selected.applications.find((item) => item.id === fixture.application.id)?.currentStage !== 'SELECTED') errors.push('Documented differing selection stage was not stored.')
  const holdReady = { ...ready, systemRecommendation: 'HOLD_FOR_REVIEW' as const }; const holdState = demoReducer(fixture.state, { type: 'ADD_FINAL_EVALUATION', payload: { evaluation: holdReady } }); const held = demoReducer(holdState, { type: 'RECORD_HUMAN_FINAL_DECISION', payload: { ...decisionPayload('HOLD', 'HIRING_MANAGER'), finalEvaluationId: holdReady.id, holdReviewDate: '2026-07-24' } }); if (held.finalEvaluations[0].humanDecision !== 'HOLD' || held.applications.find((item) => item.id === fixture.application.id)?.currentStage !== 'HOLD') errors.push('HOLD decision stage was not recorded.')
  const challenge = { id: createEvaluationChallengeId([], ready.id), finalEvaluationId: ready.id, reason: 'WRONG_TRANSCRIPT_MAPPING' as const, explanation: 'The mapped segment belongs to a different approved interview question.', questionAssessmentIds: [ready.questionAssessments[0].id], competencyAssessmentIds: [ready.competencyAssessments[0].id], transcriptSegmentIds: [...ready.questionAssessments[0].transcriptSegmentIds], evidenceIds: [...ready.questionAssessments[0].evidenceIds], status: 'OPEN' as const, createdBy: 'Validation Recruiter', createdAt: '2026-07-17T05:10:00.000Z' }; const challenged = demoReducer(added, { type: 'ADD_EVALUATION_CHALLENGE', payload: { challenge, actorRole: 'RECRUITER' } }); if (challenged.evaluationChallenges.length !== 1 || challenged.finalEvaluations[0].weightedEvidenceScore !== ready.weightedEvidenceScore) errors.push('Challenge changed score or was not stored.')
  const resolved = demoReducer(challenged, { type: 'RESOLVE_EVALUATION_CHALLENGE', payload: { challengeId: challenge.id, resolutionNote: 'The transcript mapping was corrected and verified.', resolvedAt: '2026-07-17T05:20:00.000Z', actorRole: 'RECRUITER' } })
  const unchangedAttempt = generateFinalEvaluation({ candidateId: fixture.candidate.id, applicationId: fixture.application.id, jobId: fixture.job.id, interviewId: fixture.interview.id, analysisId: fixture.analysis.id, rubric: fixture.rubric, questions: fixture.set.questions, answerSegments: fixture.transcript.segments.map((item) => ({ id: item.id, questionId: item.questionId, text: item.text })), evidence: fixture.evidence, analysis: fixture.analysis, transcript: fixture.transcript, sessionProgress: fixture.session.questionProgress, existingEvaluations: [ready], generatedAt: '2026-07-17T05:22:00.000Z' }).finalEvaluation
  if (demoReducer(resolved, { type: 'ADD_RECALCULATED_FINAL_EVALUATION', payload: { previousEvaluationId: ready.id, evaluation: unchangedAttempt } }) !== resolved) errors.push('Unchanged evidence allowed recalculation.')
  const correctedTranscript = { ...fixture.transcript, updatedAt: '2026-07-17T05:25:00.000Z', segments: fixture.transcript.segments.map((item, index) => index === 0 ? { ...item, questionId: fixture.set.questions[0].id, updatedAt: '2026-07-17T05:25:00.000Z' } : item) }
  const correctedAnalysis = { ...fixture.analysis, updatedAt: '2026-07-17T05:25:00.000Z', evidence: fixture.analysis.evidence.map((item, index) => index === 0 ? { ...item, questionIds: [fixture.set.questions[0].id], updatedAt: '2026-07-17T05:25:00.000Z' } : item) }
  const correctedState = { ...resolved, interviewTranscripts: [correctedTranscript], interviewAnalyses: [correctedAnalysis] }
  const v1Snapshot = JSON.stringify(correctedState.finalEvaluations[0])
  const recalculated = generateFinalEvaluation({ candidateId: fixture.candidate.id, applicationId: fixture.application.id, jobId: fixture.job.id, interviewId: fixture.interview.id, analysisId: correctedAnalysis.id, rubric: fixture.rubric, questions: fixture.set.questions, answerSegments: correctedTranscript.segments.map((item) => ({ id: item.id, questionId: item.questionId, text: item.text })), evidence: correctedAnalysis.evidence, analysis: correctedAnalysis, transcript: correctedTranscript, sessionProgress: fixture.session.questionProgress, existingEvaluations: [ready], generatedAt: '2026-07-17T05:30:00.000Z' }).finalEvaluation
  const versioned = demoReducer(correctedState, { type: 'ADD_RECALCULATED_FINAL_EVALUATION', payload: { previousEvaluationId: ready.id, evaluation: recalculated } })
  if (versioned.finalEvaluations.length !== 2 || versioned.finalEvaluations[1].version !== 2 || JSON.stringify(versioned.finalEvaluations[0]) !== v1Snapshot) errors.push('Recalculation did not preserve immutable version history.')
  if (demoReducer(rejected, { type: 'ADD_RECALCULATED_FINAL_EVALUATION', payload: { previousEvaluationId: ready.id, evaluation: recalculated } }) !== rejected) errors.push('Decided evaluation was recalculated.')
  const dashboard = selectFinalDecisionDashboardSummary(added); if (dashboard.readyForDecision !== 1 || selectFinalEvaluationPreparationStatus(added, fixture.candidate.id, fixture.application.id) !== 'READY_FOR_DECISION') errors.push('Dashboard or candidate decision status is incorrect.')
  const timeline = selectCandidateTimeline(rejected, fixture.application.id); if (!timeline.some((item) => item.type === 'SYSTEM_FINAL_EVALUATION_PREPARED') || !timeline.some((item) => item.type === 'FINAL_DECISION_RECORDED')) errors.push('Final evaluation or decision timeline event is missing.')
  if (rejected.communications.length !== added.communications.length) errors.push('Final decision sent candidate communication.')
  const normalized = normalizePersistedDemoState(JSON.parse(JSON.stringify(rejected))); if (normalized.finalEvaluations[0].humanDecision !== 'REJECTED' || normalized.evaluationChallenges.length !== 0) errors.push('Persistence did not restore final evaluation state.')
  try { JSON.stringify(versioned) } catch { errors.push('Final decision state is not JSON serializable.') }
  if (JSON.stringify(fixture.initial) !== JSON.stringify(createFinalEvaluationValidationFixture().initial)) errors.push('Initial state changed.')
  return { valid: errors.length === 0, errors }
}
