import { createInterviewSession, createInterviewSessionId } from '../services/interviewSessionInitialization'
import { generateInterviewQuestions } from '../services/interviewQuestionGeneration'
import { createInitialDemoState } from '../store/demoInitialState'
import { demoReducer } from '../store/demoReducer'
import { deriveJobRequirements } from './jobRequirements'
import { recoverInterruptedInterviewSessions } from '../store/demoPersistence'
import type { DemoState } from '../store/demoStateTypes'
import type { InterviewQuestionSet } from '../types/interviewQuestionSet'

export type InterviewSessionValidationResult = { valid: boolean; errors: string[] }
export function validateInterviewSessionDomain(): InterviewSessionValidationResult {
  const errors: string[] = []; const initial = createInitialDemoState(); const interview = initial.interviews.find((item) => item.status === 'SCHEDULED'); const application = initial.applications.find((item) => item.id === interview?.applicationId); const candidate = initial.candidates.find((item) => item.id === application?.candidateId); const job = initial.jobs.find((item) => item.id === application?.jobId)
  if (!interview || !application || !candidate || !job) return { valid: false, errors: ['Session fixtures could not be resolved.'] }
  const stamp = '2026-07-16T12:00:00.000Z'; const generated = generateInterviewQuestions({ interview, application, candidate, job, requirements: deriveJobRequirements(job), durationMinutes: 45 }); const set: InterviewQuestionSet = { id: `question-set-${interview.id}-v099`, interviewId: interview.id, version: 99, status: 'APPROVED', questions: generated.questions.map((question) => ({ ...question, status: 'APPROVED' })), approvedAt: stamp, approvedBy: 'Recruitment Team', createdAt: stamp, updatedAt: stamp }
  let state: DemoState = { ...initial, interviewQuestionSets: [set] }; const session = createInterviewSession({ interview, questionSet: set, createdAt: stamp })
  if (session.id !== createInterviewSessionId(interview.id) || session.status !== 'NOT_STARTED' || session.questionProgress.length !== set.questions.length || session.questionProgress.some((item) => item.status !== 'NOT_ASKED')) errors.push('Session initialization is invalid.')
  state = demoReducer(state, { type: 'ADD_INTERVIEW_SESSION', payload: { session } }); const duplicate = demoReducer(state, { type: 'ADD_INTERVIEW_SESSION', payload: { session } }); if (duplicate !== state) errors.push('Duplicate session was not prevented.')
  state = demoReducer(state, { type: 'START_INTERVIEW_SESSION', payload: { sessionId: session.id, startedAt: stamp } }); let active = state.interviewSessions[0]; if (active.status !== 'IN_PROGRESS' || state.interviews.find((item) => item.id === interview.id)?.status !== 'IN_PROGRESS' || state.applications.find((item) => item.id === interview.applicationId)?.currentStage !== 'INTERVIEW' || active.questionProgress.filter((item) => item.status === 'CURRENT').length !== 1) errors.push('Session start transition failed.')
  const first = active.currentQuestionId!; state = demoReducer(state, { type: 'UPDATE_SESSION_QUESTION_NOTES', payload: { sessionId: session.id, questionId: first, notes: 'Specific evidence captured.', updatedAt: stamp } }); state = demoReducer(state, { type: 'ADD_SESSION_FOLLOW_UP', payload: { sessionId: session.id, questionId: first, followUp: 'Ask for ownership details.', updatedAt: stamp } }); const noDuplicate = demoReducer(state, { type: 'ADD_SESSION_FOLLOW_UP', payload: { sessionId: session.id, questionId: first, followUp: '  ask for ownership details. ', updatedAt: stamp } }); if (noDuplicate !== state) errors.push('Duplicate follow-up was accepted.')
  state = demoReducer(state, { type: 'MARK_SESSION_QUESTION_ASKED', payload: { sessionId: session.id, questionId: first, completedAt: stamp } }); active = state.interviewSessions[0]; if (active.questionProgress[0].status !== 'ASKED' || !active.questionProgress[0].completedAt || active.questionProgress[1].status !== 'CURRENT') errors.push('Asked transition failed.')
  const second = active.currentQuestionId!; state = demoReducer(state, { type: 'MARK_SESSION_QUESTION_SKIPPED', payload: { sessionId: session.id, questionId: second, skippedAt: stamp } }); if (state.interviewSessions[0].questionProgress[1].status !== 'SKIPPED' || !state.interviewSessions[0].questionProgress[1].skippedAt) errors.push('Skipped transition failed.')
  state = demoReducer(state, { type: 'UPDATE_INTERVIEW_SESSION_GENERAL_NOTES', payload: { sessionId: session.id, notes: 'Overall logistics note.', updatedAt: stamp } }); state = demoReducer(state, { type: 'PAUSE_INTERVIEW_SESSION', payload: { sessionId: session.id, pausedAt: stamp, activeSecondsSinceResume: 120 } }); if (state.interviewSessions[0].status !== 'PAUSED' || state.interviewSessions[0].accumulatedActiveSeconds !== 120) errors.push('Pause or accumulated time failed.')
  state = demoReducer(state, { type: 'RESUME_INTERVIEW_SESSION', payload: { sessionId: session.id, resumedAt: stamp } }); if (state.interviewSessions[0].status !== 'IN_PROGRESS' || state.interviewSessions[0].accumulatedActiveSeconds !== 120) errors.push('Resume failed.')
  const recovered = recoverInterruptedInterviewSessions(state); if (recovered.interviewSessions[0].status !== 'PAUSED' || recovered.interviewSessions[0].questionProgress[0].interviewerNotes !== 'Specific evidence captured.') errors.push('Interrupted session recovery failed.')
  state = demoReducer(state, { type: 'COMPLETE_INTERVIEW_SESSION', payload: { sessionId: session.id, completedAt: stamp, activeSecondsSinceResume: 30 } }); const completed = state.interviewSessions[0]; if (completed.status !== 'COMPLETED' || completed.accumulatedActiveSeconds !== 150 || completed.questionProgress.some((item) => item.status === 'CURRENT' || item.status === 'NOT_ASKED') || state.interviews.find((item) => item.id === interview.id)?.status !== 'COMPLETED' || state.applications.find((item) => item.id === interview.applicationId)?.currentStage !== 'FINAL_REVIEW') errors.push('Session completion failed.')
  const readOnly = demoReducer(state, { type: 'UPDATE_INTERVIEW_SESSION_GENERAL_NOTES', payload: { sessionId: session.id, notes: 'Forbidden edit', updatedAt: stamp } }); if (readOnly !== state) errors.push('Completed session remained editable.')
  if (JSON.stringify(initial) !== JSON.stringify(createInitialDemoState()) || JSON.stringify(state).includes('undefined')) errors.push('Initial state or serialization behavior is invalid.')
  return { valid: errors.length === 0, errors }
}
